title: 'Exploring User Preferences in the Online Painting Community: A Comparative Analysis of Human-Created and AI-Generated Artwork on pixiv.net'
bibliography: bibliography.bib
csl: ieee.csl
metadata-files:
  - _pdf.yml
